backend:
  name: git-gateway
  branch: main   # hoặc master nếu repo bạn dùng master

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "homepage_en"
    label: "Homepage (English)"
    files:
      - file: "en/index.html"
        label: "Home EN"
        name: "home_en"
        fields:
          - { label: "Hero Heading", name: "hero_heading", widget: "string" }
          - { label: "Intro Text", name: "intro_text", widget: "text" }

  - name: "homepage_vn"
    label: "Homepage (Vietnamese)"
    files:
      - file: "vn/index.html"
        label: "Home VN"
        name: "home_vn"
        fields:
          - { label: "Hero Heading", name: "hero_heading", widget: "string" }
          - { label: "Intro Text", name: "intro_text", widget: "text" }
